import uuid
from typing import List

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from src.domain.ports.agent_service import IAgentService, MessageInputDTO

router = APIRouter()


class ConnectionManager:
    def __init__(self):
        self.active_connections: List[WebSocket] = []

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)

    def disconnect(self, websocket: WebSocket):
        if websocket in self.active_connections:
            self.active_connections.remove(websocket)

    async def send_personal_message(self, message: str, websocket: WebSocket):
        await websocket.send_text(message)


manager = ConnectionManager()
_agent_service: IAgentService | None = None


def init_router(agent: IAgentService):
    global _agent_service
    _agent_service = agent


@router.websocket("/ws/chat")
async def websocket_endpoint(websocket: WebSocket):
    await manager.connect(websocket)
    thread_id = str(uuid.uuid4())
    try:
        while True:
            # Receive JSON instead of text
            data = await websocket.receive_json()
            if not _agent_service:
                await websocket.send_json({"type": "error", "message": "Agent offline."})
                continue

            # Extract message content based on the JSON protocol
            # Expected client format: {"message": "Hello"}
            user_msg = data.get("message", "")
            dto = MessageInputDTO(message=user_msg)
            
            # Invoke the Agent
            result = await _agent_service.invoke_agent(thread_id, [dto])

            # Process generic chat response
            if result.message:
                await websocket.send_json({
                    "type": "chat",
                    "message": result.message
                })

            # Process Client Actions generated by the LLM
            if result.client_actions:
                for action in result.client_actions:
                    await websocket.send_json({
                        "type": "client_action",
                        "action_type": action.action_type,
                        "payload": action.payload
                    })

            # Existing generic handlers
            if result.reconstructed_pdf:
                await websocket.send_json({
                    "type": "system",
                    "message": "PDF file generated."
                })
    except WebSocketDisconnect:
        manager.disconnect(websocket)
